# Generated by Django 2.0.1 on 2018-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_logouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notehistory',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
