# Generated by Django 2.0.1 on 2018-01-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180123_1838'),
        ('dashboard', '0004_notehistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('agent', models.CharField(max_length=120)),
                ('status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logouthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='loginHistory',
        ),
        migrations.DeleteModel(
            name='logoutHistory',
        ),
    ]
