# Generated by Django 2.0.1 on 2018-01-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180123_1838'),
        ('dashboard', '0005_auto_20180130_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='logHistory',
        ),
    ]
