# Generated by Django 2.0.1 on 2018-01-23 14:36

from django.db import migrations, models
import django.db.models.deletion
import note.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('textNote', models.TextField()),
                ('background', models.CharField(default='#ffffff', max_length=7)),
                ('timePost', models.DateTimeField(auto_now_add=True)),
                ('timeEditPost', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('userName', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('avatar', models.ImageField(default='avatar/account.png', upload_to=note.models.up_img)),
                ('active', models.BooleanField(default=True)),
                ('timeSignUp', models.DateTimeField(auto_now_add=True)),
                ('UpdateUser', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.User'),
        ),
    ]
